apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "argostack"
  namespace: "argocd"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/bukowa/k8start.git
    path: charts/argostack
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: false
      allowEmpty: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
