argo_workflows:
  values: |
    server:
      extraArgs:
        - --auth-mode=server
      ingress:
        enabled: true
        ingressClassName: nginx
    #    annotations:
    #      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        hosts: &hosts
          - argoworkflow.mydev
    #    tls:
    #      - secretName: argocd-secret
    #        hosts: *hosts

#  parameters:
#    key: value

argo_events:
  values: |
    configs:
      ## NATS event bus
      nats:
        # -- Supported versions of NATS event bus
        versions:
          - version: latest
            natsStreamingImage: nats-streaming:latest
            metricsExporterImage: natsio/prometheus-nats-exporter:latest
          - version: 0.22.1
            natsStreamingImage: nats-streaming:0.22.1
            metricsExporterImage: natsio/prometheus-nats-exporter:0.9.3
#  parameters:
#    key: value

argo_rollouts:
  values: |
    dashboard:
      enabled: true
      ingress:
        enabled: true
        ingressClassName: nginx
    #    annotations:
    #      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        hosts: &hosts
          - argorollouts.mydev
    #    tls:
    #      - secretName: argocd-secret
    #        hosts: *hosts

#  parameters:
#    key: value

argocd:
  project: "default"
  namespace: "argocd"
  spec:
    destination:
      server: https://kubernetes.default.svc
      namespace: "argostack"
    source:
      repoURL: https://github.com/bukowa/k8start
      targetRevision: HEAD
