apiVersion: v1
kind: Namespace
metadata:
  name: "example"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "example"
  namespace: "example"
spec:
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: nginx
          image: "nginx:alpine"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: "example"
  namespace: "example"
spec:
  ports:
    - name: "nginx"
      port: 80
      targetPort: 80
  selector:
    app: app
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "example"
  namespace: "example"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production-http01"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - example.devit.ovh
      secretName: "example-cert"
  rules:
    - host: example.devit.ovh
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "example"
                port:
                  name: "nginx"
