apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress
  namespace: argocd
spec:
  project: default
  source:
    chart: ingress-nginx
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.2.5
    helm:
      releaseName: ingress-nginx
      values: |
        controller:
          service:
            annotations:
              service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: 'true'
              service.beta.kubernetes.io/do-loadbalancer-hostname: "only-for-internal-use.devit.ovh"
          config:
            use-proxy-protocol: 'true'
  destination:
    server: "https://kubernetes.default.svc"
    namespace: ingress-nginx
