apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress
  namespace: argocd
spec:
  project: default
  source:
    chart: nginx-ingress
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.2.5
    helm:
      releaseName: ingress-nginx
  destination:
    server: "https://kubernetes.default.svc"
    namespace: ingress-nginx
