spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/bukowa/k8start
    targetRevision: HEAD

argocd:
  project: default
  namespace: &argocd-namespace argocd

cert_manager:
  name: cert-manager
  namespace: cert-manager
  chartVersion: v1.9.1
  parameters:
    - name: installCRDs
      value: 'true'
#  values: |

cert_manager_issuers:
  name: cert-manager-issuers
  parameters:
    - name: name
      value: issuers
    - name: cluster_issuer
      value: &cluster_issuer "letsencrypt-production-http01"

argocd_ingress:
  name: argocd-ingress
  namespace: *argocd-namespace
  parameters:
    - name: cluster_issuer
      value: *cluster_issuer
    - name: host
      value: argocd.devit.ovh
    - name: namespace
      value: *argocd-namespace

http_check:
  name: http-check
  namespace: &http-check-namespace http-check
  parameters:
    - name: name
      value: "http-check"
    - name: namespace
      value: *http-check-namespace
    - name: host
      value: "httpcheck.devit.ovh"
    - name: cluster_issuer
      value: *cluster_issuer

ingress:
  name: nginx-ingress
  namespace: nginx-ingress
  chartVersion: 4.2.5
  values: |
    controller:
      service:
        annotations:
          service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: 'true'
          service.beta.kubernetes.io/do-loadbalancer-hostname: "only-for-internal-use.devit.ovh"
      config:
        use-proxy-protocol: 'true'
      extraArgs:
        enable-ssl-passthrough: ""
