apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.ingress.name }}
  namespace: {{ .Values.argocd.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argocd.project }}
  source:
    chart: ingress-nginx
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: {{ .Values.ingress.chartVersion }}
    helm:
      releaseName: ingress-nginx
      {{ if .Values.ingress.values}}
      values: {{ toYaml .Values.ingress.values | indent 6 }}
      {{ end}}
      {{- if .Values.ingress.parameters }}
      parameters:
      {{- range $key, $value := .Values.ingress.parameters }}
        - name: {{$key}}
          value: {{$value | quote}}
      {{- end }}
      {{- end}}
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: {{ .Values.ingress.namespace }}

  syncPolicy:
    automated: { }
    syncOptions:
      - CreateNamespace=true