#
#  wait {
#    fields = {
#      "status.health.status" = "Healthy"
#      "status.resources[0].health.status" = "Healthy"
#      "status.resources[1].health.status" = "Healthy"
#    }
#  }
convert:
	tfk8s -f deploy.yaml -o webstack.tf
