cert_manager:
  enabled: true
  parameters:
    installCRDs: 'true'
#  values: |
#    # empty file

ingress:
  enabled: true
  provider: "k3d"
  providers:
    digitalocean:
        parameters:
          controller.service.annotations.service.beta.kubernetes.io/do-loadbalancer-name: "k8start"
          # required for cert-manager http acme solver to work
          # https://github.com/digitalocean/digitalocean-cloud-controller-manager/blob/master/docs/controllers/services/examples/README.md#accessing-pods-over-a-managed-load-balancer-from-inside-the-cluster
          service.beta.kubernetes.io/do-loadbalancer-hostname: "only-for-internal-use.devit.ovh"
          controller.service.annotations.service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: 'true'
          controller.service.config.use-proxy-protocol: 'true'
#        values: |
#          # empty file
    k3d:
        parameters:
          controller.service.annotations.ingress.running.in.k3d.dummy: "true"
          controller.metrics.enabled: "true"
          controller.podAnnotations."prometheus\.io/scrape": "true"
          controller.podAnnotations."prometheus\.io/port": "10254"
          controller.config.enable-access-log-for-default-backend: "true"
        values: |
          controller:
            extraArgs:
              # name of this service can be tricky
              # if this backend is not reachable controller wont start with error
              # No service with name webstack-http-headers found in namespace webstack
              default-backend-service: webstack/webstack-http-headers

http_headers:
  enabled: true
  values: |
    ingress:
      annotations:
        # argocd default health check for ingress won't work in our case;
        # our ingress controller is deployed after this ingress
        # this should always sync after ingress controller
        # i wonder if that will work
        argocd.argoproj.io/sync-wave: "1"

argocd:
  project: "default"
  namespace: "argocd"
  spec:
    destination:
      server: https://kubernetes.default.svc
      namespace: "webstack"
    source:
      repoURL: https://github.com/bukowa/k8start
      targetRevision: HEAD
