apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: loki-distributed
    repoURL: "https://grafana.github.io/helm-charts"
    targetRevision: "0.63.2"
    helm:
      releaseName: loki
      values: |
        ingester:
          persistence:
            enabled: true
            size: 2Gi
            storageClass: longhorn
        querier:
          persistence:
            enabled: true
            size: 2Gi
            storageClass: longhorn
        compactor:
          persistence:
            enabled: true
            size: 2Gi
            storageClass: longhorn
        ruler:
          persistence:
            enabled: true
            size: 2Gi
            storageClass: longhorn
        indexgateway:
          persistence:
            enabled: true
            size: 2Gi
            storageClass: longhorn
  destination:
    server: https://kubernetes.default.svc
    namespace: promstack
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true