controller:

  replicaCount: 4
  affinity:
    podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                    - ingress-nginx
            topologyKey: kubernetes.io/hostname
  service:
    # preserve source ip
    externalTrafficPolicy: "Local"
#    type: "NodePort"
#    nodePorts:
#      http: 31000
#      https: 32000
#      tcp:
#        8080: 33000
#
#  hostPort:
#    enabled: false
#    ports:
#      http: 80
#      https: 443

  extraArgs:
    watch-ingress-without-class: true

  config:
    proxy-body-size: 5000m
    enable-access-log-for-default-backend: true
