{{ if .Values.default_backend.enabled}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Release.Name }}-default-backend
  namespace: {{ .Values.argocd.namespace }}
  annotations:
    # always run before ingress controller if used as default backend
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argocd.project }}
  source:
    chart: http-headers
    repoURL: https://bukowa.github.io/http-headers/
    targetRevision: 0.2.0
    helm:
      releaseName: {{ .Release.Name }}-default-backend
      {{- template "argo.helm.values" .Values.default_backend }}
  destination:
    server: {{ .Values.argocd.spec.destination.server }}
    namespace: {{ .Values.argocd.spec.destination.namespace }}
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
{{end}}
