apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.cluster_issuer_staging }}
  namespace: {{ .Values.namespace }}
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: {{ .Values.cluster_issuer_staging }}
    solvers:
      - http01:
          ingress:
            class: nginx
