apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: "event-one"
  namespace: "argostack"
spec:
  template:
    serviceAccountName: "event-one"
  dependencies:
    - name: "eventone-dependency"
      eventSourceName: "event-one"
      eventName: "example"
  triggers:
    - template:
        name: webhook-pod-trigger
        k8s:
          operation: create
          source:
            resource:
              apiVersion: v1
              kind: Pod
              metadata:
                generateName: hello-world-
              spec:
                containers:
                  - name: hello-container
                    args:
                      - "hello-world"
                    command:
                      - cowsay
                    image: "docker/whalesay:latest"
          parameters:
            - src:
                dependencyName: eventone-dependency
                dataKey: body
              dest: spec.containers.0.args.0
#    - template:
#        name: webhook-deployment-trigger
#        k8s:
#          operation: create
#          source:
#            resource:
#              apiVersion: apps/v1
#              kind: Deployment
#              metadata:
#                generateName: hello-world-
#              spec:
#                replicas: 1
#                selector:
#                  matchLabels:
#                    app: mydeploy
#                template:
#                  metadata:
#                    labels:
#                      app: mydeploy
#                  spec:
#                    containers:
#                      - name: hello-container
#                        args:
#                         - "hello world"
#                        command:
#                         - cowsay
#                        image: "docker/whalesay:latest"