apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace}}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: headers
          image: quay.io/examples/go-http-headers:master
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name}}
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: "headers"
  selector:
    app: app
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.name}}
  namespace: {{ .Values.namespace }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.cluster_issuer }}
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.host}}
      secretName: {{ .Values.cert_secret}}
  rules:
    - host: {{ .Values.host}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.name}}
                port:
                  name: "headers"
