apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: issuers
  namespace: {{ .Values.argocd.namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .Values.cert_manager.namespace}}
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.argocd.project }}
  source:
    path: cert-manager
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}

  syncPolicy:
    automated: { }
    syncOptions:
      - CreateNamespace=true
