apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.cert_manager_issuers.name }}
  namespace: {{ .Values.argocd.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .Values.cert_manager.namespace}}
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.argocd.project }}
  source:
    path: cert-issuers
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      parameters:
        - name: namespace
          value: {{ .Values.cert_manager.namespace }}

  syncPolicy:
    automated: { }
    syncOptions:
      - CreateNamespace=true
