apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: httpcheck
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: httpcheck
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: httpcheck
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}

  syncPolicy:
    automated: { }
    syncOptions:
      - CreateNamespace=true