apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Release.Name }}-argo-workflows
  namespace: {{ .Values.argocd.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argocd.project }}
  destination:
    namespace: {{ .Values.argocd.spec.destination.namespace }}
    server: {{ .Values.argocd.spec.destination.server }}
  source:
    chart: argo-workflows
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 0.20.1
    helm:
      releaseName: {{ .Release.Name }}
      {{- template "argo.helm.values" .Values.argo_workflows }}
  syncPolicy:
    automated: { }
    syncOptions:
      - CreateNamespace=true
