name: test provision k3d

on:
  push:
    branches:
      - "*"

jobs:
  test_k3d:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: test k3d
        env:
          TF_VAR_k3d_servers: 1
        working-directory:
          ./provision/k3d
        run: |
          set -x
          export KUBECONFIG=$PWD/.kube/config
          export TF_VAR_kube_config_path=$KUBECONFIG
          kubectl version --client=true
          curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash
          make || export MAKE_EXIT=$? 
          kubectl get -A pods -o go-template='{{- range .items -}} {{$item := .}} {{- range .status.containerStatuses}} {{- if .state.waiting }} {{- $item.metadata.namespace}}  {{ $item.metadata.name}} {{- printf "\n" -}} {{end}}{{end}}{{end}}' | xargs -n 2 kubectl logs --namespace $1 $2
          kubectl get -A pods -o go-template='{{- range .items -}} {{$item := .}} {{- range .status.containerStatuses}} {{- if .state.waiting }} {{- $item.metadata.namespace}}  {{ $item.metadata.name}} {{ .state}}  {{- printf "\n============================\n" -}} {{end}}{{end}}{{end}}'
          exit $MAKE_EXIT
